//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _420_476_ProjetFinal_Desrosiers_Pucacco_Lam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int id { get; set; }
        public Nullable<int> requestId { get; set; }
        public Nullable<bool> notifResult { get; set; }
        public string type { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
