//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _420_476_ProjetFinal_Desrosiers_Pucacco_Lam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int id { get; set; }
        public string text { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public string image { get; set; }
        public Nullable<int> creatorId { get; set; }
        public Nullable<int> matchedUserID { get; set; }
        public Nullable<int> categoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Notification Notification { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
